# To get started with Dependabot version updates, you'll need to specify which
# package ecosystems to update and where the package manifests are located.
# Please see the documentation for all configuration options:
# https://docs.github.com/code-security/dependabot/dependabot-version-updates/configuration-options-for-the-dependabot.yml-file

version: 2
updates:
  # Update JavaScript dependencies in /client/ (React Native frontend)
  - package-ecosystem: "npm"
    directory: "/client"
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 5
    reviewers:
      - "Ze0r099"
    labels:
      - "dependencies"
      - "frontend"

  # Update JavaScript dependencies in /server/ (Node.js backend)
  - package-ecosystem: "npm"
    directory: "/server"
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 5
    reviewers:
      - "Ze0r099"
    labels:
      - "dependencies"
      - "backend"

  # Update JavaScript dependencies in /blockchain/ (Hardhat for smart contracts)
  - package-ecosystem: "npm"
    directory: "/blockchain"
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 5
    reviewers:
      - "Ze0r099"
    labels:
      - "dependencies"
      - "blockchain"

  # Update Docker dependencies (docker-compose.yml in root)
  - package-ecosystem: "docker"
    directory: "/"
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 5
    reviewers:
      - "Ze0r099"
    labels:
      - "dependencies"
      - "docker"
